import type { PoseDefinition } from '../types/index.ts';

export const mountainPose: PoseDefinition = {
  id: 'yoga_mountain',
  name: 'Mountain Pose (Tadasana)',
  category: 'yoga',
  difficulty: 'beginner',
  description: 'Stand tall with feet together, arms at sides, weight evenly distributed. The foundation of all standing poses.',
  contraindications: ['low blood pressure', 'headache', 'insomnia'],
  jointTargets: [
    { jointName: 'trunk_inclination', idealAngleDegrees: 0, toleranceDegrees: 5, critical: true, weight: 0.25 },
    { jointName: 'cervical_alignment', idealAngleDegrees: 0, toleranceDegrees: 5, critical: true, weight: 0.2 },
    { jointName: 'knee_extension_left', idealAngleDegrees: 180, toleranceDegrees: 5, critical: false, weight: 0.1 },
    { jointName: 'knee_extension_right', idealAngleDegrees: 180, toleranceDegrees: 5, critical: false, weight: 0.1 },
    { jointName: 'hip_alignment', idealAngleDegrees: 0, toleranceDegrees: 5, critical: true, weight: 0.2 },
    { jointName: 'shoulder_abduction', idealAngleDegrees: 0, toleranceDegrees: 10, critical: false, weight: 0.15 },
  ],
  alignmentChecks: [
    { checkName: 'hips_level', description: 'Hips should be level within 8 degrees', thresholdDegrees: 8, critical: true },
    { checkName: 'shoulders_level', description: 'Shoulders should be level within 8 degrees', thresholdDegrees: 8, critical: true },
    { checkName: 'weight_centered', description: 'Weight evenly distributed between both feet', thresholdDegrees: 5, critical: true },
  ],
  phases: [
    { name: 'entry', criteria: { jointTargets: { trunk_inclination: 5 }, alignmentChecks: ['hips_level', 'shoulders_level'] } },
    { name: 'hold', criteria: { jointTargets: { trunk_inclination: 0 }, alignmentChecks: ['hips_level', 'shoulders_level', 'weight_centered'] }, durationSeconds: 30 },
    { name: 'release', criteria: { jointTargets: { trunk_inclination: 10 }, alignmentChecks: [] } },
  ],
  mistakePatterns: [
    {
      code: 'forward_head',
      name: 'Forward Head Posture',
      description: 'Head is positioned forward of the shoulders',
      severity: 'medium',
      conditions: [{ type: 'alignment', checkName: 'cervical_alignment', operator: 'gt', value: 10 }],
      userMessage: 'Gently draw your head back over your shoulders',
      trainerNote: 'Client exhibits forward head carriage — suggest chin tuck exercises',
      affectedLandmarks: [0, 11, 12],
    },
    {
      code: 'hips_shifted',
      name: 'Uneven Hip Load',
      description: 'One hip is higher than the other',
      severity: 'medium',
      conditions: [{ type: 'alignment', checkName: 'hips_level', operator: 'gt', value: 8 }],
      userMessage: 'Level your hips — shift weight onto the back foot',
      trainerNote: 'Weight distribution asymmetry detected. Check for standing leg preference.',
      affectedLandmarks: [23, 24],
    },
    {
      code: 'shoulders_elevated',
      name: 'Elevated Shoulders',
      description: 'Shoulders are hunched toward the ears',
      severity: 'low',
      conditions: [{ type: 'alignment', checkName: 'shoulders_level', operator: 'gt', value: 8 }],
      userMessage: 'Relax your shoulders away from your ears',
      trainerNote: 'Chronic shoulder elevation — consider upper trap stretching',
      affectedLandmarks: [11, 12],
    },
  ],
  coachingCues: [
    'Press evenly through all four corners of both feet',
    'Engage your quadriceps to lift the kneecaps',
    'Lengthen your tailbone toward the floor',
    'Draw your shoulder blades down your back',
  ],
};

export const warriorI: PoseDefinition = {
  id: 'yoga_warrior_i',
  name: 'Warrior I (Virabhadrasana I)',
  category: 'yoga',
  difficulty: 'intermediate',
  description: 'Stand with legs wide apart, front knee bent, arms raised overhead, hips squared forward.',
  contraindications: ['hip injury', 'knee injury', 'low back pain'],
  jointTargets: [
    { jointName: 'front_knee_flexion', idealAngleDegrees: 90, toleranceDegrees: 10, critical: true, weight: 0.25 },
    { jointName: 'back_knee_extension', idealAngleDegrees: 180, toleranceDegrees: 10, critical: false, weight: 0.1 },
    { jointName: 'trunk_inclination', idealAngleDegrees: 0, toleranceDegrees: 8, critical: true, weight: 0.2 },
    { jointName: 'hips_squared', idealAngleDegrees: 0, toleranceDegrees: 15, critical: true, weight: 0.2 },
    { jointName: 'shoulder_flexion_overhead', idealAngleDegrees: 180, toleranceDegrees: 15, critical: false, weight: 0.15 },
    { jointName: 'back_ankle_angle', idealAngleDegrees: 45, toleranceDegrees: 10, critical: false, weight: 0.1 },
  ],
  alignmentChecks: [
    { checkName: 'hips_forward', description: 'Hips should face the front of the mat', thresholdDegrees: 15, critical: true },
    { checkName: 'front_knee_over_ankle', description: 'Front knee aligns with ankle', thresholdDegrees: 10, critical: true },
    { checkName: 'back_heel_down', description: 'Back heel presses into the floor', thresholdDegrees: 5, critical: false },
  ],
  phases: [
    { name: 'entry', criteria: { jointTargets: { front_knee_flexion: 120 }, alignmentChecks: ['hips_forward'] } },
    { name: 'hold', criteria: { jointTargets: { front_knee_flexion: 90 }, alignmentChecks: ['hips_forward', 'front_knee_over_ankle'] }, durationSeconds: 30 },
    { name: 'release', criteria: { jointTargets: { front_knee_flexion: 160 }, alignmentChecks: [] } },
  ],
  mistakePatterns: [
    {
      code: 'hips_open',
      name: 'Hips Open to Side',
      description: 'Hips rotate toward the front leg instead of staying squared',
      severity: 'medium',
      conditions: [{ type: 'alignment', checkName: 'hips_forward', operator: 'gt', value: 15 }],
      userMessage: 'Square your hips to the front of the mat',
      trainerNote: 'Hip openness reduces the hip flexor stretch on the back leg',
      affectedLandmarks: [23, 24],
    },
    {
      code: 'back_heel_lift',
      name: 'Back Heel Lifting',
      description: 'Back heel lifts off the floor',
      severity: 'low',
      conditions: [{ type: 'alignment', checkName: 'back_heel_down', operator: 'gt', value: 5 }],
      userMessage: 'Press your back heel firmly into the floor',
      trainerNote: 'Shorten your stance if the back heel cannot stay down',
      affectedLandmarks: [28, 30],
    },
  ],
  coachingCues: [
    'Root down through the outer edge of your back foot',
    'Draw your hip points toward each other to square the hips',
    'Reach your arms alongside your ears, palms facing each other',
    'Soften your shoulders away from your ears',
  ],
};

export const warriorII: PoseDefinition = {
  id: 'yoga_warrior_ii',
  name: 'Warrior II (Virabhadrasana II)',
  category: 'yoga',
  difficulty: 'intermediate',
  description: 'Stand with legs wide apart, front knee bent at 90°, arms parallel to the floor, gaze over front hand.',
  contraindications: ['hip injury', 'knee injury', 'ankle injury'],
  jointTargets: [
    { jointName: 'front_knee_flexion', idealAngleDegrees: 90, toleranceDegrees: 10, critical: true, weight: 0.3 },
    { jointName: 'back_knee_extension', idealAngleDegrees: 180, toleranceDegrees: 10, critical: false, weight: 0.1 },
    { jointName: 'trunk_inclination', idealAngleDegrees: 0, toleranceDegrees: 8, critical: true, weight: 0.2 },
    { jointName: 'front_hip_flexion', idealAngleDegrees: 90, toleranceDegrees: 15, critical: false, weight: 0.1 },
    { jointName: 'front_shoulder_abduction', idealAngleDegrees: 90, toleranceDegrees: 15, critical: false, weight: 0.15 },
    { jointName: 'back_shoulder_abduction', idealAngleDegrees: 90, toleranceDegrees: 15, critical: false, weight: 0.15 },
  ],
  alignmentChecks: [
    { checkName: 'front_knee_over_ankle', description: 'Front knee should align with ankle, not beyond toes', thresholdDegrees: 10, critical: true },
    { checkName: 'hips_squared', description: 'Hips should face the long edge of the mat', thresholdDegrees: 15, critical: true },
    { checkName: 'arms_parallel_floor', description: 'Arms should be parallel to the floor', thresholdDegrees: 10, critical: false },
  ],
  phases: [
    { name: 'entry', criteria: { jointTargets: { front_knee_flexion: 120 }, alignmentChecks: ['front_knee_over_ankle'] } },
    { name: 'hold', criteria: { jointTargets: { front_knee_flexion: 90 }, alignmentChecks: ['front_knee_over_ankle', 'hips_squared'] }, durationSeconds: 30 },
    { name: 'release', criteria: { jointTargets: { front_knee_flexion: 160 }, alignmentChecks: [] } },
  ],
  mistakePatterns: [
    {
      code: 'knee_over_toe',
      name: 'Knee Past Ankle',
      description: 'Front knee extends beyond the ankle joint',
      severity: 'high',
      conditions: [{ type: 'joint_angle', jointName: 'front_knee_flexion', operator: 'lt', value: 80 }],
      userMessage: 'Shift your weight back — keep your knee above your ankle',
      trainerNote: 'Knee tracking past ankle increases shear force on ACL. Cue posterior weight shift.',
      affectedLandmarks: [23, 25, 27],
    },
    {
      code: 'front_arm_drooping',
      name: 'Front Arm Drooping',
      description: 'Front arm has dropped below shoulder height',
      severity: 'low',
      conditions: [{ type: 'joint_angle', jointName: 'front_shoulder_abduction', operator: 'lt', value: 75 }],
      userMessage: 'Lift your front arm to shoulder height',
      trainerNote: 'Fatigue in deltoids — consider shorter hold duration or regression',
      affectedLandmarks: [11, 13, 15],
    },
    {
      code: 'hip_open',
      name: 'Hips Not Squared',
      description: 'Hips are rotated toward the front leg',
      severity: 'medium',
      conditions: [{ type: 'alignment', checkName: 'hips_squared', operator: 'gt', value: 15 }],
      userMessage: 'Square your hips to the side wall',
      trainerNote: 'Hip opening indicates inadequate hip flexor mobility or lack of awareness',
      affectedLandmarks: [23, 24],
    },
  ],
  coachingCues: [
    'Keep your front knee tracking over the second toe',
    'Press firmly through the outer edge of your back foot',
    'Reach actively through both arms',
    'Maintain a long spine — do not lean forward',
  ],
};

export const treePose: PoseDefinition = {
  id: 'yoga_tree',
  name: 'Tree Pose (Vrksasana)',
  category: 'yoga',
  difficulty: 'intermediate',
  description: 'Stand on one leg, place the other foot on the inner thigh or calf, arms raised overhead.',
  contraindications: ['ankle injury', 'knee injury', 'balance disorders'],
  jointTargets: [
    { jointName: 'standing_knee_extension', idealAngleDegrees: 180, toleranceDegrees: 5, critical: true, weight: 0.2 },
    { jointName: 'bent_hip_abduction', idealAngleDegrees: 45, toleranceDegrees: 15, critical: false, weight: 0.15 },
    { jointName: 'bent_hip_flexion', idealAngleDegrees: 45, toleranceDegrees: 15, critical: false, weight: 0.15 },
    { jointName: 'trunk_inclination', idealAngleDegrees: 0, toleranceDegrees: 5, critical: true, weight: 0.25 },
    { jointName: 'shoulder_flexion_overhead', idealAngleDegrees: 180, toleranceDegrees: 15, critical: false, weight: 0.15 },
    { jointName: 'pelvis_level', idealAngleDegrees: 0, toleranceDegrees: 5, critical: true, weight: 0.1 },
  ],
  alignmentChecks: [
    { checkName: 'hips_level', description: 'Hips should remain level, standing hip not hiking', thresholdDegrees: 5, critical: true },
    { checkName: 'standing_foot_grounded', description: 'Standing foot should be firmly rooted', thresholdDegrees: 5, critical: true },
    { checkName: 'gaze_focused', description: 'Gaze should be steady on a fixed point', thresholdDegrees: 0, critical: false },
  ],
  phases: [
    { name: 'entry', criteria: { jointTargets: { bent_hip_abduction: 30 }, alignmentChecks: ['hips_level'] } },
    { name: 'hold', criteria: { jointTargets: { bent_hip_abduction: 45 }, alignmentChecks: ['hips_level', 'standing_foot_grounded'] }, durationSeconds: 30 },
    { name: 'release', criteria: { jointTargets: { bent_hip_abduction: 0 }, alignmentChecks: [] } },
  ],
  mistakePatterns: [
    {
      code: 'foot_on_knee',
      name: 'Foot Pressing Into Knee',
      description: 'The lifted foot is placed directly on the knee joint',
      severity: 'high',
      conditions: [{ type: 'alignment', checkName: 'bent_hip_flexion', operator: 'lt', value: 30 }],
      userMessage: 'Place your foot on your inner thigh or calf, never directly on the knee',
      trainerNote: 'Lateral pressure on the knee joint can cause injury',
      affectedLandmarks: [25, 26],
    },
    {
      code: 'standing_leg_locked',
      name: 'Standing Leg Hyperextended',
      description: 'The standing leg is locked straight',
      severity: 'low',
      conditions: [{ type: 'joint_angle', jointName: 'standing_knee_extension', operator: 'gt', value: 180 }],
      userMessage: 'Keep a micro-bend in your standing knee',
      trainerNote: 'Hyperextension stresses the knee joint',
      affectedLandmarks: [25, 26],
    },
    {
      code: 'hip_hiking',
      name: 'Standing Hip Hiking',
      description: 'Standing hip hikes up to compensate',
      severity: 'medium',
      conditions: [{ type: 'alignment', checkName: 'hips_level', operator: 'gt', value: 5 }],
      userMessage: 'Keep your hips level — press your standing foot down',
      trainerNote: 'Hiking indicates weak glute medius on the standing leg',
      affectedLandmarks: [23, 24],
    },
  ],
  coachingCues: [
    'Find a steady focal point with your gaze',
    'Press your foot into your thigh and your thigh back into your foot',
    'Lengthen your tailbone toward the floor',
    'Raise your arms overhead with palms together or separate',
  ],
};

export const downwardDog: PoseDefinition = {
  id: 'yoga_downward_dog',
  name: 'Downward-Facing Dog (Adho Mukha Svanasana)',
  category: 'yoga',
  difficulty: 'intermediate',
  description: 'On hands and knees, lift the hips up and back, forming an inverted V-shape.',
  contraindications: ['carpal tunnel syndrome', 'high blood pressure', 'glaucoma'],
  jointTargets: [
    { jointName: 'hip_flexion', idealAngleDegrees: 90, toleranceDegrees: 15, critical: false, weight: 0.2 },
    { jointName: 'knee_extension', idealAngleDegrees: 180, toleranceDegrees: 10, critical: false, weight: 0.15 },
    { jointName: 'ankle_dorsiflexion', idealAngleDegrees: 30, toleranceDegrees: 10, critical: false, weight: 0.1 },
    { jointName: 'shoulder_flexion', idealAngleDegrees: 120, toleranceDegrees: 15, critical: true, weight: 0.25 },
    { jointName: 'spine_length', idealAngleDegrees: 180, toleranceDegrees: 10, critical: true, weight: 0.2 },
    { jointName: 'elbow_extension', idealAngleDegrees: 180, toleranceDegrees: 5, critical: false, weight: 0.1 },
  ],
  alignmentChecks: [
    { checkName: 'spine_straight', description: 'Spine should be long, not rounded', thresholdDegrees: 10, critical: true },
    { checkName: 'heels_toward_floor', description: 'Heels should press toward the floor', thresholdDegrees: 15, critical: false },
    { checkName: 'head_between_arms', description: 'Head should hang between the upper arms', thresholdDegrees: 10, critical: false },
  ],
  phases: [
    { name: 'entry', criteria: { jointTargets: { shoulder_flexion: 90, hip_flexion: 60 }, alignmentChecks: ['spine_straight'] } },
    { name: 'hold', criteria: { jointTargets: { shoulder_flexion: 120, hip_flexion: 90, knee_extension: 180 }, alignmentChecks: ['spine_straight'] }, durationSeconds: 30 },
    { name: 'release', criteria: { jointTargets: { hip_flexion: 60 }, alignmentChecks: ['spine_straight'] } },
  ],
  mistakePatterns: [
    {
      code: 'rounded_back',
      name: 'Rounded Spine',
      description: 'The upper back is rounded instead of long',
      severity: 'medium',
      conditions: [{ type: 'alignment', checkName: 'spine_straight', operator: 'gt', value: 10 }],
      userMessage: 'Lengthen your spine — bend your knees if needed',
      trainerNote: 'Tight hamstrings or poor shoulder mobility — bending knees is acceptable',
      affectedLandmarks: [11, 12, 23, 24],
    },
    {
      code: 'head_hanging',
      name: 'Head Drooping',
      description: 'Head hangs too low, compressing the neck',
      severity: 'low',
      conditions: [{ type: 'alignment', checkName: 'head_between_arms', operator: 'gt', value: 10 }],
      userMessage: 'Keep your head between your upper arms',
      trainerNote: 'Neck strain — cue looking slightly forward between the hands',
      affectedLandmarks: [0, 7, 8],
    },
  ],
  coachingCues: [
    'Press your hands firmly into the mat, spread your fingers wide',
    'Lift your sitting bones toward the ceiling',
    'Pedal your heels alternately to stretch the calves',
    'Draw your shoulder blades toward each other',
  ],
};

export const childsPose: PoseDefinition = {
  id: 'yoga_childs_pose',
  name: "Child's Pose (Balasana)",
  category: 'yoga',
  difficulty: 'beginner',
  description: 'Kneeling, sit back on the heels and fold forward, resting the forehead on the floor.',
  contraindications: ['knee injury', 'diarrhea', 'pregnancy (advanced)'],
  jointTargets: [
    { jointName: 'knee_flexion', idealAngleDegrees: 135, toleranceDegrees: 15, critical: false, weight: 0.2 },
    { jointName: 'hip_flexion', idealAngleDegrees: 120, toleranceDegrees: 20, critical: false, weight: 0.2 },
    { jointName: 'trunk_flexion', idealAngleDegrees: 45, toleranceDegrees: 15, critical: false, weight: 0.2 },
    { jointName: 'shoulder_flexion', idealAngleDegrees: 180, toleranceDegrees: 20, critical: false, weight: 0.2 },
    { jointName: 'cervical_flexion', idealAngleDegrees: 45, toleranceDegrees: 15, critical: false, weight: 0.2 },
  ],
  alignmentChecks: [
    { checkName: 'hips_to_heels', description: 'Sitting bones should rest toward the heels', thresholdDegrees: 15, critical: false },
    { checkName: 'forehead_floor', description: 'Forehead should rest on the floor or a prop', thresholdDegrees: 10, critical: false },
  ],
  phases: [
    { name: 'entry', criteria: { jointTargets: { hip_flexion: 90 }, alignmentChecks: [] } },
    { name: 'hold', criteria: { jointTargets: { hip_flexion: 120, trunk_flexion: 45 }, alignmentChecks: [] }, durationSeconds: 60 },
    { name: 'release', criteria: { jointTargets: { trunk_flexion: 0 }, alignmentChecks: [] } },
  ],
  mistakePatterns: [
    {
      code: 'knees_apart',
      name: 'Knees Too Wide or Too Narrow',
      description: 'Knee position is unstable',
      severity: 'low',
      conditions: [{ type: 'alignment', checkName: 'hips_to_heels', operator: 'gt', value: 15 }],
      userMessage: 'Bring your knees to a comfortable width',
      trainerNote: 'Adjust knee width to find stability',
      affectedLandmarks: [25, 26],
    },
  ],
  coachingCues: [
    'Walk your hands forward and lengthen through your fingertips',
    'Soften your shoulder blades down your back',
    'Breathe into the back of your ribs',
    'If your forehead does not reach the floor, use a block or fists',
  ],
};

export const cobraPose: PoseDefinition = {
  id: 'yoga_cobra',
  name: 'Cobra Pose (Bhujangasana)',
  category: 'yoga',
  difficulty: 'beginner',
  description: 'Lying on the stomach, press the hands into the floor and lift the chest. A gentle backbend.',
  contraindications: ['back injury', 'carpal tunnel syndrome', 'pregnancy'],
  jointTargets: [
    { jointName: 'spinal_extension', idealAngleDegrees: 15, toleranceDegrees: 10, critical: false, weight: 0.3 },
    { jointName: 'shoulder_extension', idealAngleDegrees: 10, toleranceDegrees: 10, critical: false, weight: 0.15 },
    { jointName: 'elbow_flexion', idealAngleDegrees: 160, toleranceDegrees: 10, critical: true, weight: 0.2 },
    { jointName: 'cervical_extension', idealAngleDegrees: 15, toleranceDegrees: 10, critical: false, weight: 0.15 },
    { jointName: 'hip_extension_lying', idealAngleDegrees: 0, toleranceDegrees: 5, critical: true, weight: 0.2 },
  ],
  alignmentChecks: [
    { checkName: 'elbows_slightly_bent', description: 'Elbows should be slightly bent, not locked', thresholdDegrees: 10, critical: true },
    { checkName: 'hips_grounded', description: 'Hips should stay pressing into the floor', thresholdDegrees: 5, critical: true },
    { checkName: 'shoulders_down', description: 'Shoulders should not shrug toward ears', thresholdDegrees: 10, critical: false },
  ],
  phases: [
    { name: 'entry', criteria: { jointTargets: { spinal_extension: 5 }, alignmentChecks: ['elbows_slightly_bent', 'hips_grounded'] } },
    { name: 'hold', criteria: { jointTargets: { spinal_extension: 15 }, alignmentChecks: ['elbows_slightly_bent', 'hips_grounded'] }, durationSeconds: 20 },
    { name: 'release', criteria: { jointTargets: { spinal_extension: 0 }, alignmentChecks: [] } },
  ],
  mistakePatterns: [
    {
      code: 'arms_locked',
      name: 'Arms Locked Straight',
      description: 'Elbows are fully locked, pushing too high into the backbend',
      severity: 'high',
      conditions: [{ type: 'alignment', checkName: 'elbows_slightly_bent', operator: 'lt', value: 150 }],
      userMessage: 'Keep your elbows slightly bent — lift only as high as your spine allows',
      trainerNote: 'Locking the elbows pushes the backbend into the lumbar spine',
      affectedLandmarks: [13, 14],
    },
    {
      code: 'hips_lifting',
      name: 'Hips Lifting Off Floor',
      description: 'Hips rise from the floor during the pose',
      severity: 'medium',
      conditions: [{ type: 'alignment', checkName: 'hips_grounded', operator: 'gt', value: 5 }],
      userMessage: 'Press your hips and pubic bone into the floor',
      trainerNote: 'Lifting hips indicates using arms instead of back muscles',
      affectedLandmarks: [23, 24],
    },
  ],
  coachingCues: [
    'Press the tops of your feet into the floor',
    'Draw your shoulder blades together and down',
    'Lift through the sternum, not the chin',
    'Keep your navel drawing slightly toward the spine',
  ],
};

export const trianglePose: PoseDefinition = {
  id: 'yoga_triangle',
  name: 'Triangle Pose (Trikonasana)',
  category: 'yoga',
  difficulty: 'intermediate',
  description: 'Stand with legs wide apart, reach forward and rotate the torso, one hand to the shin or floor, other arm raised.',
  contraindications: ['neck injury', 'hip injury', 'low blood pressure'],
  jointTargets: [
    { jointName: 'front_hip_flexion', idealAngleDegrees: 90, toleranceDegrees: 15, critical: false, weight: 0.15 },
    { jointName: 'trunk_rotation', idealAngleDegrees: 90, toleranceDegrees: 15, critical: true, weight: 0.25 },
    { jointName: 'trunk_lateral_flexion', idealAngleDegrees: 15, toleranceDegrees: 10, critical: false, weight: 0.15 },
    { jointName: 'front_knee_extension', idealAngleDegrees: 180, toleranceDegrees: 5, critical: true, weight: 0.15 },
    { jointName: 'back_knee_extension', idealAngleDegrees: 180, toleranceDegrees: 5, critical: true, weight: 0.1 },
    { jointName: 'top_shoulder_abduction', idealAngleDegrees: 90, toleranceDegrees: 15, critical: false, weight: 0.1 },
    { jointName: 'cervical_rotation', idealAngleDegrees: 90, toleranceDegrees: 20, critical: false, weight: 0.1 },
  ],
  alignmentChecks: [
    { checkName: 'front_knee_straight', description: 'Front leg should remain straight', thresholdDegrees: 5, critical: true },
    { checkName: 'hips_open', description: 'Hips should be open to the side', thresholdDegrees: 15, critical: true },
    { checkName: 'stacked_shoulders', description: 'Shoulders should be stacked vertically', thresholdDegrees: 15, critical: false },
  ],
  phases: [
    { name: 'entry', criteria: { jointTargets: { front_hip_flexion: 60 }, alignmentChecks: ['front_knee_straight'] } },
    { name: 'hold', criteria: { jointTargets: { trunk_rotation: 90, trunk_lateral_flexion: 15 }, alignmentChecks: ['front_knee_straight', 'hips_open'] }, durationSeconds: 30 },
    { name: 'release', criteria: { jointTargets: { trunk_rotation: 0 }, alignmentChecks: [] } },
  ],
  mistakePatterns: [
    {
      code: 'front_knee_bent',
      name: 'Front Knee Bending',
      description: 'The front knee bends during the lateral movement',
      severity: 'medium',
      conditions: [{ type: 'alignment', checkName: 'front_knee_straight', operator: 'gt', value: 5 }],
      userMessage: 'Keep your front leg straight by engaging your quadriceps',
      trainerNote: 'Bent front knee reduces hamstring stretch and stability',
      affectedLandmarks: [25, 26],
    },
    {
      code: 'hips_closed',
      name: 'Hips Not Open',
      description: 'Hips remain facing forward instead of opening to the side',
      severity: 'medium',
      conditions: [{ type: 'alignment', checkName: 'hips_open', operator: 'gt', value: 15 }],
      userMessage: 'Open your hips toward the side wall',
      trainerNote: 'Closed hips limit the lateral stretch and rotation',
      affectedLandmarks: [23, 24],
    },
  ],
  coachingCues: [
    'Reach your front hand to your shin, ankle, or a block — not the floor',
    'Open your chest toward the side wall',
    'Stack your top shoulder directly over your bottom shoulder',
    'Gaze toward your top thumb',
  ],
};

export const seatedForwardBend: PoseDefinition = {
  id: 'yoga_seated_forward_bend',
  name: 'Seated Forward Bend (Paschimottanasana)',
  category: 'yoga',
  difficulty: 'intermediate',
  description: 'Seated with legs extended forward, hinge at the hips and reach toward the feet.',
  contraindications: ['herniated disc', 'sciatica (acute)', 'asthma'],
  jointTargets: [
    { jointName: 'hip_flexion', idealAngleDegrees: 120, toleranceDegrees: 20, critical: false, weight: 0.3 },
    { jointName: 'knee_extension', idealAngleDegrees: 180, toleranceDegrees: 5, critical: true, weight: 0.25 },
    { jointName: 'trunk_flexion', idealAngleDegrees: 45, toleranceDegrees: 15, critical: false, weight: 0.2 },
    { jointName: 'cervical_flexion', idealAngleDegrees: 20, toleranceDegrees: 15, critical: false, weight: 0.15 },
    { jointName: 'ankle_dorsiflexion', idealAngleDegrees: 10, toleranceDegrees: 10, critical: false, weight: 0.1 },
  ],
  alignmentChecks: [
    { checkName: 'knees_straight', description: 'Both knees should remain straight', thresholdDegrees: 5, critical: true },
    { checkName: 'spine_long', description: 'Spine should lengthen before folding', thresholdDegrees: 10, critical: false },
    { checkName: 'feet_flexed', description: 'Feet should be actively flexed toward the body', thresholdDegrees: 10, critical: false },
  ],
  phases: [
    { name: 'entry', criteria: { jointTargets: { hip_flexion: 90 }, alignmentChecks: ['knees_straight'] } },
    { name: 'hold', criteria: { jointTargets: { hip_flexion: 120 }, alignmentChecks: ['knees_straight'] }, durationSeconds: 30 },
    { name: 'release', criteria: { jointTargets: { hip_flexion: 90 }, alignmentChecks: [] } },
  ],
  mistakePatterns: [
    {
      code: 'knees_bent',
      name: 'Knees Bending',
      description: 'One or both knees bend to reach further forward',
      severity: 'medium',
      conditions: [{ type: 'alignment', checkName: 'knees_straight', operator: 'gt', value: 5 }],
      userMessage: 'Keep your legs straight — use a strap around your feet if needed',
      trainerNote: 'Bending knees defeats the hamstring stretch purpose',
      affectedLandmarks: [25, 26],
    },
    {
      code: 'back_rounding',
      name: 'Rounding From the Back',
      description: 'Folding forward from the lower back instead of hinging at the hips',
      severity: 'medium',
      conditions: [{ type: 'alignment', checkName: 'spine_long', operator: 'gt', value: 10 }],
      userMessage: 'Hinge from your hips — keep a long spine',
      trainerNote: 'Spinal flexion under load can aggravate disc issues',
      affectedLandmarks: [11, 12, 23, 24],
    },
  ],
  coachingCues: [
    'Sit up tall and lengthen through your spine before folding',
    'Hinge from the hips, not the lower back',
    'Reach for your shins, ankles, or feet — wherever you can reach with a straight back',
    'Flex your feet actively toward you',
  ],
};

export const bridgePose: PoseDefinition = {
  id: 'yoga_bridge',
  name: 'Bridge Pose (Setu Bandha Sarvangasana)',
  category: 'yoga',
  difficulty: 'beginner',
  description: 'Lying on the back with knees bent, lift the hips toward the ceiling. A gentle backbend.',
  contraindications: ['neck injury', 'knee injury', 'high blood pressure'],
  jointTargets: [
    { jointName: 'hip_extension', idealAngleDegrees: 20, toleranceDegrees: 10, critical: false, weight: 0.3 },
    { jointName: 'knee_flexion', idealAngleDegrees: 90, toleranceDegrees: 10, critical: true, weight: 0.2 },
    { jointName: 'spinal_extension', idealAngleDegrees: 10, toleranceDegrees: 10, critical: false, weight: 0.2 },
    { jointName: 'cervical_neutral', idealAngleDegrees: 0, toleranceDegrees: 10, critical: true, weight: 0.15 },
    { jointName: 'ankle_angle', idealAngleDegrees: 90, toleranceDegrees: 10, critical: false, weight: 0.15 },
  ],
  alignmentChecks: [
    { checkName: 'knees_hip_width', description: 'Knees should remain hip-width apart', thresholdDegrees: 10, critical: true },
    { checkName: 'knees_over_ankles', description: 'Knees should align over the ankles', thresholdDegrees: 10, critical: true },
    { checkName: 'weight_shoulders', description: 'Weight should be on the shoulders, not the neck', thresholdDegrees: 5, critical: true },
  ],
  phases: [
    { name: 'entry', criteria: { jointTargets: { hip_extension: 5 }, alignmentChecks: ['knees_hip_width', 'knees_over_ankles'] } },
    { name: 'hold', criteria: { jointTargets: { hip_extension: 20 }, alignmentChecks: ['knees_hip_width', 'knees_over_ankles'] }, durationSeconds: 30 },
    { name: 'release', criteria: { jointTargets: { hip_extension: 0 }, alignmentChecks: ['knees_hip_width'] } },
  ],
  mistakePatterns: [
    {
      code: 'knees_splaying',
      name: 'Knees Splaying Apart',
      description: 'Knees fall outward during the lift',
      severity: 'medium',
      conditions: [{ type: 'alignment', checkName: 'knees_hip_width', operator: 'gt', value: 10 }],
      userMessage: 'Keep your knees hip-width apart — engage your inner thighs',
      trainerNote: 'Splaying knees indicates adductor weakness',
      affectedLandmarks: [25, 26],
    },
    {
      code: 'neck_crunching',
      name: 'Weight on Neck',
      description: 'Weight shifts onto the neck instead of the shoulders',
      severity: 'high',
      conditions: [{ type: 'alignment', checkName: 'weight_shoulders', operator: 'gt', value: 5 }],
      userMessage: 'Press through your shoulders, not your neck',
      trainerNote: 'Neck compression risk — remind client to keep a brick under the sacrum',
      affectedLandmarks: [0, 7, 8],
    },
  ],
  coachingCues: [
    'Press evenly through both feet',
    'Engage your glutes to lift your hips — not your lower back',
    'Interlace your hands under your back and press your arms down',
    'Roll your shoulders underneath you to create space for the neck',
  ],
};
